### ISSUE TITLE
Distinguish better between read/unread and selected threads in Gmail

### ISSUE THREAD

**Issue by damemi** [DM164/Dark-by-DM#32]
Hi, this style looks great but it's visually a little difficult to tell between read/unread emails and the currently selected email (when using the reading pane). I hacked together a higher-contrast setting for these classes but an actual supported update by the maintainers would be awesome!

Before:
![Screen Shot 2020-11-16 at 10 27 02 AM](https://user-images.githubusercontent.com/1839101/99273030-7e56fc00-27f6-11eb-93a6-a1ae980448d6.png)

My changes:
```css
/* unread */
.zE {
    color: #c7c7c7;
    /* background: rgb(35, 35, 35); <- current value*/
    background-color: #333;
    border-left: 3px solid #4b70ab;
}

/* selected conversation */
.aps {
    background-color: #111;
}
```
After:
![Screen Shot 2020-11-16 at 10 25 42 AM](https://user-images.githubusercontent.com/1839101/99273048-844cdd00-27f6-11eb-906c-a8ff80a62914.png)
